### PR TITLE
Update MobileDetect

### PR DESCRIPTION
**Pull request by Xon**
Version 1.3.4
- Updated with the version 2.8.26 of the MobileDetect class
- "Detailed browser fingerprinting" allows disabling detailed fingerprint if you just care if the user is on something mobile-like

Remove some unused code

### CODE REVIEW

**Comment by cclaerhout** [comment]
The archived versions were there to detect faster the new devices that have been added. In your update, I don't see any (during the init) new ones.

I will check

**Comment by Xon** [comment]
This commit; https://github.com/cclaerhout/xen_BrowserDetection/pull/2/commits/e0bf81fd055fb4e2fe7f191ee5ee78b56c2931e6 lets you more easily see new devices.

```
NokiaLumia
NokiaLumiaTablet
MpmanTablet
KocasoTablet
HisenseTablet
```

**Comment by Xon** [comment]
Simplified how the code loops over the array, so the list of devices is only defined once

**Comment by cclaerhout** [comment]
Great thanks ! 🥇

**Comment by Xon** [comment]
@cclaerhout any chance you could release this on xenforo.com's resource manager when you have the time?

**Pull request merged**
